### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by leepowelldev** [ruanmartinelli/npm-workspaces-demo#2]
Sorry, still trying to figure out workspaces, so in the root install I `npm install` to which npm symlinks `package-a` and `package-b` - great.

But if I then go into the `package-b` directory and run `npm install` again (assuming I had other dependencies in there), I get a `package-a - NotFound` error.

Am I missing something?

Edit:
In fact at this point, I can't add any other dependencies to `package-b` as each time it attempts to resolve `package-a` and can't find it. The only way I can see this being any use is like so:

```
// package-b/package.json
{
  // ...
  "workspaces": ["../package-a"]
}
```

At which point, `package-a` is symlinked in `package-b` node_modules and I can use `package-b` as normal.

**Comment by ruanmartinelli** [comment]
Hey @leepowelldev!

> [...] if I then go into the package-b directory and run npm install again (assuming I had other dependencies in there), I get a package-a - NotFound error.

This works for me, can you confirm which npm version you have running?

**Comment by leepowelldev** [comment]
Hi - I'm on 7.1.0, can you just document your steps to getting it working?

```
❯ npm i

added 2 packages, and audited 4 packages in 616ms

found 0 vulnerabilities

~/Sites/npm-workspaces-demo

❯ cd packages/package-b

~/Sites/npm-workspaces-demo/packages/package-b

❯ npm i
npm ERR! code ENOVERSIONS
npm ERR! No versions available for package-a

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-12-07T16_04_40_502Z-debug.log

~/Sites/npm-workspaces-demo/packages/package-b
❯ 
```

**Comment by leepowelldev** [comment]
OK, so after a bit of playing, I see that NPM installs all the dependencies for both packages to the top level, great ... however it still won't install new dependencies in the package if it has a dependency on one of the others. Here I try to add `lodash` to `package-b`:

```
❯ npm i        

added 2 packages, and audited 4 packages in 626ms

found 0 vulnerabilities

~/Sites/npm-workspaces-demo

❯ cd packages/package-b

~/Sites/npm-workspaces-demo/packages/package-b

❯ npm i lodash     
npm ERR! code ENOVERSIONS
npm ERR! No versions available for package-a

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2020-12-07T17_27_17_771Z-debug.log
```

**Comment by ruanmartinelli** [comment]
Ok, so I took a second look into this.

When you run commands inside the packages, there's no workspace awareness. `npm install` fails when it sees a `"package-a": "1.0.0"`.

If you install `lodash` on the root and add it manually to `package-a`'s package.json for example, I believe it will work ([example](https://github.com/ruanmartinelli/npm-workspaces-demo/tree/playground)). This should become easier when they release something like `npm workspaces package-a lodash` in the future.

[This](https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md#expanding-on-symlinking-structure-and-package-lock-file-shape) might be helpful too.
